spring:
  application:
    name: spring-mvc-practice202605
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB #한 파일당 5메가 제한
      max-request-size: 20MB #한 요청당


blog:
  file-directory: /Users/haurto/Desktop/dev/upload